controller_list:
  - name: fake_ur_group_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_sweep_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
      - wrist_yaw_joint
  - name: fake_ee_robot_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: ur_group
    pose: home